### PR TITLE
Add UK Imperial units

### PR DESCRIPTION
**Pull request by Tirpitz93**
I needed this a while ago for a project I was working on.
I extended it to include many more units than I needed, I hope this is useful to someone.

### CODE REVIEW

**Comment by trzemecki** [comment]
Doesn't work.
```
    inch                    = unit('inch' ,          0.0254 * M,         'Inch')
TypeError: unbound method unit() must be called with Unum instance as first argument (got str instance instead)
```

I've change units creation comparing to original repo. Now new units are created by **new_unit** function from **unum.core** package.

**Comment by Tirpitz93** [comment]
I will rework it then and resubmit

**Comment by Tirpitz93** [comment]
I believe this works now, and is more structured/useful

**Comment by Tirpitz93** [comment]
This also adds standard gravity as a unit in `others` as `g0`

**Pull request merged**
